# ISS 1.3  This is a freely available demo version of ISS lacking
# many features and vulnerability checks from the commercial version.
# Please send e-mail to iss@iss.net for more information.

iss:	iss.o telnet.h
	$(CC) -o $@ iss.o

clean:
	rm -f iss iss.o
