.TH CARP2PS 1 "Feb 13, 1992"
.UC 4
.SH NAME
carp2ps \- Converts \fIcarp\fP(1) output into postscript code.
.SH SYNOPSIS
.B carp2ps
carp_result_filename
.SH DESCRIPTION
.I carp2ps
reads a standard \fIcarp\fP(1) input file and emits postscript.
.SH SEE ALSO
carp(1)
.SH BUGS
Assumes correct carp output as its input.
