#! /bin/sh
# @(#)unload	1.24 3/22/92

PATH=/usr/ucb:/bin:/usr/bin:/usr/etc ; export PATH

MIDF="/tmp/MODULE_ID"

if ( test -f $MIDF ) then
	
	if(modunload -id `cat $MIDF`) then
		rm $MIDF
	else
		modstat
		exit 1
	fi
else
	echo "no $MIDF file present"
	exit 1
fi	
exit 0
